#pragma once
#include <map>
#include <string>

namespace hotkeys {

enum State {
  DOWN,
  UP,
};

enum Keys {
  SC_GRAVE = 0x29,
  SC_1 = 0x02,
  SC_2 = 0x03,
  SC_3 = 0x04,
  SC_4 = 0x05,
  SC_5 = 0x06,
  SC_6 = 0x07,
  SC_7 = 0x08,
  SC_8 = 0x09,
  SC_9 = 0x0a,
  SC_0 = 0x0b,
  SC_MINUS = 0x0c,
  SC_EQUALS = 0x0d,
  SC_BACKSPACE = 0x0E,

  SC_TAB = 0x0f,
  SC_Q = 0x10,
  SC_W = 0x11,
  SC_E = 0x12,
  SC_R = 0x13,
  SC_T = 0x14,
  SC_Y = 0x15,
  SC_U = 0x16,
  SC_I = 0x17,
  SC_O = 0x18,
  SC_P = 0x19,
  SC_LEFTBRACKET = 0x1a,
  SC_RIGHTBRACKET = 0x1b,
  SC_SLASH = 0x2b,

  SC_CAPSLOCK = 0x3a,
  SC_A = 0x1e,
  SC_S = 0x1f,
  SC_D = 0x20,
  SC_F = 0x21,
  SC_G = 0x22,
  SC_H = 0x23,
  SC_J = 0x24,
  SC_K = 0x25,
  SC_L = 0x26,
  SC_SEMICOLON = 0x27,
  SC_APOSTROPHE = 0x28,
  SC_NONEUSMULTIPLY = 0x2b,
  SC_ENTER = 0x1c,

  SC_LSHIFT = 0x2a,
  SC_LESS = 0x56,
  SC_Z = 0x2c,
  SC_X = 0x2d,
  SC_C = 0x2e,
  SC_V = 0x2f,
  SC_B = 0x30,
  SC_N = 0x31,
  SC_M = 0x32,
  SC_COMMA = 0x33,
  SC_PERIOD = 0x34,
  SC_BACKSLASH = 0x35,
  SC_RSHIT = 0x36,

  SC_LCTRL = 0x1d,
  SC_LALT = 0x38,
  SC_SPACE = 0x39,
  SC_RALT = 0x138,
  SC_RCTRL = 0x11d,

  SC_INSERT = 0x152,
  SC_DELETE = 0x153,
  SC_LEFT = 0x14b,
  SC_HOME = 0x147,
  SC_END = 0x14f,
  SC_UP = 0x148,
  SC_DOWN = 0x150,
  SC_PAGEUP = 0x149,
  SC_PAGEDOWN = 0x151,
  SC_RIGHT = 0x14d,

  SC_KP_NUMLOCK = 0x145,
  SC_KP_7 = 0x47,
  SC_KP_4 = 0x4b,
  SC_KP_1 = 0x4f,
  SC_KP_BACKSLASH = 0x35,
  SC_KP_8 = 0x48,
  SC_KP_5 = 0x4C,
  SC_KP_2 = 0x50,
  SC_KP_0 = 0x52,
  SC_KP_MULTIPLY = 0x137,
  SC_KP_9 = 0x49,
  SC_KP_6 = 0x4d,
  SC_KP_3 = 0x51,
  SC_KP_PERIOD = 0x53,
  SC_KP_MINUS = 0x4a,
  SC_KP_PLUS = 0x4e,
  SC_KP_ENTER = 0x11c,

  SC_ESCAPE = 0x01,
  SC_F1 = 0x3b,
  SC_F2 = 0x3c,
  SC_F3 = 0x3d,
  SC_F4 = 0x3e,
  SC_F5 = 0x3f,
  SC_F6 = 0x40,
  SC_F7 = 0x41,
  SC_F8 = 0x42,
  SC_F9 = 0x43,
  SC_F10 = 0x44,
  SC_F11 = 0x57,
  SC_F12 = 0x58,
  SC_PRINTSCREEN = 0x137,
  SC_SCROLLOCK = 0x46,
  SC_PAUSE = 0x45
};

std::map<Keys, std::string> keynames = {
    {SC_GRAVE, ","},
    {SC_1, "1"},
    {SC_2, "2"},
    {SC_3, "3"},
    {SC_4, "4"},
    {SC_5, "5"},
    {SC_6, "6"},
    {SC_7, "7"},
    {SC_8, "8"},
    {SC_9, "9"},
    {SC_0, "0"},
    {SC_MINUS, "-"},
    {SC_EQUALS, "="},
    {SC_BACKSPACE, "backspace"},

    {SC_TAB, "tab"},
    {SC_Q, "q"},
    {SC_W, "w"},
    {SC_E, "e"},
    {SC_R, "r"},
    {SC_T, "t"},
    {SC_Y, "y"},
    {SC_U, "u"},
    {SC_I, "i"},
    {SC_O, "o"},
    {SC_P, "p"},
    {SC_LEFTBRACKET, "["},
    {SC_RIGHTBRACKET, "]"},
    {SC_SLASH, "\\"},

    {SC_CAPSLOCK, "capslock"},
    {SC_A, "a"},
    {SC_S, "s"},
    {SC_D, "d"},
    {SC_F, "f"},
    {SC_G, "g"},
    {SC_H, "h"},
    {SC_J, "j"},
    {SC_K, "k"},
    {SC_L, "l"},
    {SC_SEMICOLON, ";"},
    {SC_APOSTROPHE, "`"},
    {SC_NONEUSMULTIPLY, "*"},
    {SC_ENTER, "enter"},

    {SC_LSHIFT, "lshift"},
    {SC_LESS, "<"},
    {SC_Z, "z"},
    {SC_X, "x"},
    {SC_C, "c"},
    {SC_V, "v"},
    {SC_B, "b"},
    {SC_N, "n"},
    {SC_M, "m"},
    {SC_COMMA, ","},
    {SC_PERIOD, "."},
    {SC_BACKSLASH, "/"},
    {SC_RSHIT, "rshift"},

    {SC_LCTRL, "lctrl"},
    {SC_LALT, "lalt"},
    {SC_SPACE, "space"},
    {SC_RALT, "ralt"},
    {SC_RCTRL, "rctrl"},

    {SC_INSERT, "insert"},
    {SC_DELETE, "delete"},
    {SC_LEFT, "left"},
    {SC_HOME, "home"},
    {SC_END, "end"},
    {SC_UP, "up"},
    {SC_DOWN, "down"},
    {SC_PAGEUP, "pageup"},
    {SC_PAGEDOWN, "pagedown"},
    {SC_RIGHT, "right"},

    {SC_KP_NUMLOCK, "numlock"},
    {SC_KP_7, "keypad_7"},
    {SC_KP_4, "keypad_4"},
    {SC_KP_1, "keypad_1"},
    {SC_KP_BACKSLASH, "keypad_/"},
    {SC_KP_8, "keypad_8"},
    {SC_KP_5, "keypad_5"},
    {SC_KP_2, "keypad_2"},
    {SC_KP_0, "keypad_0"},
    {SC_KP_MULTIPLY, "keypad_*"},
    {SC_KP_9, "keypad_9"},
    {SC_KP_6, "keypad_6"},
    {SC_KP_3, "keypad_3"},
    {SC_KP_PERIOD, "keypad_."},
    {SC_KP_MINUS, "keypad_-"},
    {SC_KP_PLUS, "keypad_+"},
    {SC_KP_ENTER, "keypad_enter"},

    {SC_ESCAPE, "escape"},
    {SC_F1, "f1"},
    {SC_F2, "f2"},
    {SC_F3, "f3"},
    {SC_F4, "f4"},
    {SC_F5, "f5"},
    {SC_F6, "f6"},
    {SC_F7, "f7"},
    {SC_F8, "f8"},
    {SC_F9, "f9"},
    {SC_F10, "f10"},
    {SC_F11, "f11"},
    {SC_F12, "f12"},
    {SC_PRINTSCREEN, "printscreen"},
    {SC_SCROLLOCK, "scrollock"},
    {SC_PAUSE, "pause"},
};
}
